Reviewer:
  - date: 2024, 2023
    object: JNCA
    href: https://www2.cloud.editorialmanager.com/jnca/default.aspx

  - date: 2024
    object: ComCom
    href: https://www.editorialmanager.com/comcom/Default.aspx

Teaching assistant:
  - date: Fall 2024
    object: Machine Learning
    href:

  - date: Fall 2023
    object: Computer Network
    href: